# Generated by Django 4.2.7 on 2024-01-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyExchange', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellerproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(null=True)),
                ('description', models.CharField(default=1, max_length=300, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm')], max_length=70, null=True)),
                ('product_image1', models.ImageField(upload_to='uploads')),
                ('product_image2', models.ImageField(null=True, upload_to='uploads')),
                ('product_image3', models.ImageField(null=True, upload_to='uploads')),
                ('product_image4', models.ImageField(null=True, upload_to='uploads')),
                ('product_image5', models.ImageField(null=True, upload_to='uploads')),
                ('Category', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EasyExchange.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyExchange.customers')),
            ],
        ),
    ]
