# Generated by Django 4.2.7 on 2024-01-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyExchange', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyExchange.customers')),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyExchange.sellerproducts')),
            ],
        ),
        migrations.CreateModel(
            name='Intrested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyExchange.customers')),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyExchange.sellerproducts')),
            ],
        ),
    ]
