# Generated by Django 4.2.7 on 2024-01-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyExchange', '0006_happy_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsatisfied_Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='happy_customers')),
                ('product_price', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=150)),
                ('product_city', models.CharField(max_length=150)),
                ('upload_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
