# Generated by Django 4.2.7 on 2024-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyExchange', '0007_unsatisfied_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproducts',
            name='description',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
